version: '3.6'

networks:
  web-network:

services:
  dungeon-revealer:
    build:
      context: ./dungeon-revealer/
      dockerfile: Dockerfile
      network: host
    user: 1000:1000
    working_dir: /usr/src/app
    container_name: dungeon-revealer
    restart: always
    command: /bin/sh -c "cp -a ./build-tmp/* ./build/ && node server-build/index.js"
    environment:
      - PC_PASSWORD=${DR_USER_PASS}
      - DM_PASSWORD=${DR_DM_PASS}
      - PUBLIC_URL="/map"
    volumes:
      - ./dungeon-revealer/data:/usr/src/app/data
      - ./dungeon-revealer/build/:/usr/src/app/build/:rw
    networks:
      - web-network

  improved-initiative:
    build:
      context: ./improved-initiative/
      dockerfile: Dockerfile
      network: host
    user: 1000:1000
    working_dir: /usr/src/app
    container_name: improved-initiative
    restart: always
    command: /bin/bash -c "cp -a ./public/* ./public-tmp/ && node server/server.js"
    environment:
      - NODE_ENV
      - PORT=4000
      - DB_CONNECTION_STRING=mongodb://mongo:27017/
    volumes:
      - ./improved-initiative/public-tmp/:/usr/src/app/public-tmp:rw
    links:
      - mongo:27017
    networks:
      - web-network

  paragon:
    build:
      context: ./paragon/
      dockerfile: Dockerfile
      network: host
    user: 1000:1000
    working_dir: /usr/src/app
    container_name: paragon
    restart: always
    command: /bin/sh -c "export PATH=$PATH:/home/node/.npm-global/bin/ && cp -a ./build-tmp/* ./build/ && serve -s build -l 3000"
    volumes:
      - ./paragon/build/:/usr/src/app/build/:rw
    networks:
      - web-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo/data:/data/db:rw
    networks:
      - web-network

  nginx:
    build:
      args:
        - ht_pass=${DR_USER_PASS}
        - ht_user=${HT_USER}
        - ht_dm_pass=${DR_DM_PASS}
        - ht_dm_user=${HT_DM_USER}
      context: ./nginx/
      dockerfile: Dockerfile
      network: host
    user: 1000:1000
    container_name: nginx
    restart: always
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/default.conf.${SSL}.template > /etc/nginx/conf.d/default.conf && envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /var/www/certbot.sh.template > /var/www/certbot.sh && bash /var/www/certbot.sh && sudo nginx -g 'daemon off;'"
    environment:
      - HTACCESS
      - DOMAIN
      - DOMAIN_EMAIL
      - DR_HOST
      - II_HOST
      - PA_HOST
      - DM_HOST
      - SSL
    volumes:
      - ./nginx/files/:/etc/nginx/
      - ./nginx/ssl/:/etc/letsencrypt/
      - ./dungeon-revealer/build/:/var/www/dungeon-revealer/:rw,cached
      - ./improved-initiative/public-tmp/:/var/www/improved-initiative/:rw
      - ./paragon/build/:/var/www/paragon/:rw
    ports:
      - '80:80'
      - '443:443'
    links:
      - dungeon-revealer:3000
      - improved-initiative:4000
      - paragon:3000
    networks:
      - web-network
    depends_on:
      - dungeon-revealer
      - improved-initiative
      - paragon
